version: '3.7'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend/app:/usr/src/app
    ports:
      - 8000:8000
    command: 'python3 manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: django
      MYSQL_PASSWORD: password
      MYSQL_USER: root
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./backend/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/var/www/frontend" 
    environment:
      CHOKIDAR_USEPOLLING: true
    command: 'npm run dev'
    ports:
      - '3001:3000'
  # nginx:
  #   build:
  #     context: ./nginx
  #   volumes:
  #     - static:/static
  #     - frontend:/var/www/frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #     - frontend

# volumes:
#   static:
#   frontend:
