version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    # depends_on: 
    #   - db
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/usr/src/app
    command: 'npm run dev'
    ports:
      - '3001:3000'
  # nginx:
  #   build:
  #     context: ./nginx
  #   volumes:
  #     - static:/static
  #     - frontend:/var/www/frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #     - frontend

volumes:
  static:
  frontend:
