version: '3.7'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend/app:/usr/src/app
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/usr/src/app
    command: 'npm run dev'
    ports:
      - '3001:3000'
  # nginx:
  #   build:
  #     context: ./nginx
  #   volumes:
  #     - static:/static
  #     - frontend:/var/www/frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #     - frontend

# volumes:
#   static:
#   frontend:
